
[task]

[task.terminal_default]
file = "file"
dependent = []
mode = "cycle"
style = "style"
operate = []
condition = "now"
state = "run_wait"
be_depended = []
describe = "Terminal default abilityset task."

[task.visual_default]
file = "file"
dependent = []
mode = "cycle"
style = "style"
operate = []
condition = "now"
state = "run_wait"
be_depended = []
describe = "Visual default abilityset task."

