
[task]

[task.visual_default]
describe = "Visual default abilityset task."
be_depended = []
state = "run_wait"
dependent = []
file = "file"
mode = "cycle"
style = "style"
operate = []
condition = "now"

[task.terminal_default]
describe = "Terminal default abilityset task."
be_depended = []
state = "run_wait"
dependent = []
file = "file"
mode = "cycle"
style = "style"
operate = []
condition = "now"

